version: '3'
services:
  mysql:
    image: mysql:8.0.22
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      - MYSQL_DATABASE=cpd
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_USER=root
      - MYSQL_PASSWORD=password

  wordpress:
    image: wordpress:php7.4-apache
    depends_on:
      - mysql
    restart: always
    environment:
      - WORDPRESS_DB_HOST=mysql
      - WORDPRESS_DB_USER=root
      - WORDPRESS_DB_NAME=cpd
      - WORDPRESS_DB_PASSWORD=password
    ports:
      - 8080:80
    links:
     - mysql
    volumes:
      - wp:/www/

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    depends_on:
      - mysql
    links:
      - mysql
    ports:
      - 8081:80
    environment:
      - PMA_HOST=mysql
      - PMA_USER=root
      - PMA_PASSWORD=password

volumes:
  db_data:
  wp: